/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: riosorio <marvin@42.fr>                    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2023/04/12 20:22:57 by riosorio          #+#    #+#             */
/*   Updated: 2023/06/03 20:18:08 by riosorio         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include "ft_printf.h"

#include <stdio.h>
int	main(void)
{
	char	*s = "hello friky world!";
	int	a;
	int	re;

	printf("###### LAST TEST ########\n");
	printf("1234567890123456789012345678901234567890123456789012345678901234567890\n");
	a = printf(" %s ", "-");
  	printf("%d\n", a);
	a = ft_printf(" %s ", "-");
  	printf("%d\n", a);
	printf("checking %%10c, %%10c, %%10c arg 'NULL'\n");
	a = printf("%10c, %10c, %10c", '5', 'x', '\n');
  	printf("%d\n", a);
	a = ft_printf("%10c, %10c, %10c", '5', 'x', '\n');
  	printf("%d\n", a);
	a = printf("%*s", 6, "pika");
  	printf("%d\n", a);
	a = ft_printf("%*s", 6, "pika");
  	printf("%d\n", a);
	printf("checking %%5c, %%5c, %%5c arg 'NULL'\n");
	a = printf("%5c, %5c, %5c", '5', 'x', '\n');
  	printf("%d\n", a);
	a = ft_printf("%5c, %5c, %5c", '5', 'x', '\n');
  	printf("%d\n", a);
	printf("checking %%.c\n");
	a =  ft_printf("%.c", 'a');
  	printf("%d\n", a);
	a =  printf("%.c", 'a');
  	printf("%d\n", a);
	printf("checking p6 %%#x\n", -1);
	a = printf("p6 %#x", -1);
  	printf("%d\n", a);
	a = ft_printf("p6 %#x", -1);
  	printf("%d\n", a);
	printf("checking %% 12.56d\n", 0);
	a = printf("% 12.56d", 0);
  	printf("%d\n", a);
	a = ft_printf("% 12.56d", 0);
  	printf("%d\n", a);
	printf("checking %% 048d!\n", 0);
	a = printf("% 048d!", 1);
  	printf("%d\n", a);
	a = ft_printf("% 048d!", 1);
  	printf("%d\n", a);
	printf("checking %% -14.2d\n", 0);
	a = printf("% -14.2d", 0);
  	printf("%d\n", a);
	a = ft_printf("% -14.2d", 0);
  	printf("%d\n", a);
	a = ft_printf("% 2.56d>------------<", 0);
  	printf("%d\n", a);
	a = printf("% 2.56d>------------<", 0);
  	printf("%d\n", a);
  	a = ft_printf("% 1s.\n", "");
  	printf("%d\n", a);
  	a = printf("% 1s.\n", "");
  	printf("%d\n", a);
	a = ft_printf("\\!/%+d\\!/\n", 0);
  	printf("%d\n", a);
  	a = ft_printf("\\!/%+d\\!/\n", -1);
  	printf("%d\n", a);

	printf("checking %% -44.40d\n", 0);
	a = ft_printf("\\!/% -44.40d\\!/", 0);
  	printf("%d\n", a);
	a = printf("\\!/% -44.40d\\!/", 0);
  	printf("%d\n", a);
	a = ft_printf("!% 34.61d!", -2085261581);
  	printf("%d\n", a);
	a = printf("!% 34.61d!", -2085261581);
  	printf("%d\n", a);
	a = ft_printf("%5c, %5c, %5c", '5', 'x', '\n');
  	printf("%d\n", a);
	a = printf("%5c, %5c, %5c", '5', 'x', '\n');
  	printf("%d\n", a); 
	a = ft_printf("%%");
	printf("valor de a: %d \n", a);
	printf("### STARTTING TEST FT_PRINTF #### \n");
	/*a = ft_printf("\\!/% 26.2d\\!/", 0);
  	printf("%d\n", a);
	a = printf("\\!/% 26.2d\\!/", 0);
  	printf("%d\n", a);
  	a = printf("%5c, %5c, %5c", '5', 'x', '\n');
  	printf("%d\n", a);
	a = printf("%--120.50d%-%%-112.167X%-32.65u" ,-1355834522,3814946551u,404243169u);
  	printf("%d\n", a);
	printf("----------------\n");
  	a = ft_printf("%5c, %5c, %5c", '5', 'x', '\n');
	printf("%d\n", a);
	a = ft_printf("%--120.50d%-%%-112.167X%-32.65u" ,-1355834522,3814946551u,404243169u);
  	printf("%d\n", a);
	ft_printf("menos %-10smenos\n", "hey");
  	ft_printf("menos %-10imenos\n", 42);
  	ft_printf("menos %-    10smenos\n", "hey");
	ft_printf("%5%.\n");
	printf("%5%.\n");
	printf("return %d\n", ft_printf("%-x.\n", 42));
	printf("return: %d\n", printf("%-x.\n", 42));
	printf("return %d\n" , printf("%5%.\n"));
	ft_printf("%-05%.\n");
	printf("%-05%.\n");
	ft_printf("%01d\n", 0);
	printf("%01d\n", 0);
	ft_printf("%02d\n", -3);
	printf("%02d\n", -1);
	ft_printf("%05d\n", 101);
	printf("%05d\n", 101);
	char name[] = "OpenAI";
	ft_printf("%s\n", name);
	ft_printf("%9s\n", name);
  	ft_printf("%.4s|\n", name);
	printf("NULL \n");
  	ft_printf("p6 %.0d\n", 100);
	a = printf("%.0i.\n", 0);
	a = ft_printf("%.0i.\n", 0);
	a = ft_printf("%.i.\n", 0);
  	a = ft_printf("%5.0i.\n", 0);
	a = ft_printf("%08.5i\n", 34);
	a = ft_printf("%08.5i\n", 34);
  	printf("%d\n", a);
	a = printf("%7i", -14);
  	printf("%d\n", a);
	a = ft_printf("%7i", -14);
  	printf("%d\n", a);
	a = ft_printf("hello %s.", "gavix");
  	printf("%d\n", a);
	a = printf("hello %s.", "gavix");
  	printf("%d\n", a);
	a = printf(" %.2d ", -1);
  	printf("%d\n", a);
	a = ft_printf(" %.2d ", -1);
  	printf("%d\n", a);
	a = printf(" %04d ", -14);
  	printf("%d\n", a);
	a = ft_printf(" %04d ", -14);
  	printf("%d\n", a);
	a = printf("%2p ", -1);
  	printf("%d\n", a);
	a = ft_printf("%2p ", -1);
  	printf("%d\n", a); 
	a = ft_printf(" %-1c %-2c %-3c ", '0', 0, '1');
  	printf("%d\n", a);
	a = printf(" %-1c %-2c %-3c ", '0', 0, '1');
  	printf("%d\n", a);
	a = printf(" %c %c %c ", '0', 0, '1');
  	printf("%d\n", a);
	a = ft_printf(" %c %c %c ", '0', 0, '1');
  	printf("%d\n", a);
	a = printf(" %c %c %c ", 0, '1', '2');
  	printf("%d\n", a);
	a = ft_printf(" %c %c %c ", 0, '1', '2');
  	printf("%d\n", a);
	a = ft_printf("%d", -10);
  	printf("%d\n", a);
	a = ft_printf("|% 1s |", "");
  	printf("%d\n", a);
	a = printf("|% 1s |", "");
  	printf("%d\n", a);
	a = ft_printf(" % 1s", "");
  	printf("%d\n", a);
	a= ft_printf(" % d ", -1);
  	printf("%d\n", a);
	a = ft_printf(" %#X ", 9);
  	printf("%d\n", a);
	a = printf(" %#X ", 9);
  	printf("%d\n", a);
	a = ft_printf(" %.2d ", -1);
  	printf("%d\n", a);
	a = printf(" %.2d ", -1);
  	printf("%d\n", a);
	ft_printf("%-020d|\n", 248);
	ft_printf("%020d\n", -248);
	a = ft_printf(" %.2d ", -1);
  	printf("%d\n", a);
  	a = ft_printf("%.s", NULL);
  	printf("%d\n", a);
	a = ft_printf("%.7s", "hello");
  	printf("%d\n", a);
	a = ft_printf("%.2s%.7s", "hello", "world");
  	printf("%d\n", a);
	a = ft_printf("%.7s%.2s", "hello", "world");
  	printf("%d\n", a);
	int number = 42;
  	a = ft_printf("%.5d", number);
  	printf("%d\n", a);
  	a = ft_printf("%.1d", number);
  	printf("%d\n", a);
  	a = ft_printf("%.0d", number);
  	printf("%d\n", a);
  	a = ft_printf("%p", number);
  	printf("%d\n", a);
  	a = ft_printf("%.5p", number);
  	printf("%d\n", a);
  	a = ft_printf("%.1p", number);
  	printf("%d\n", a);

	a = ft_printf(" %04d ", -14);
	printf("a: %d\n", a);
	a = printf(" %04d ", -14);
	printf("a: %d\n", a);
	a = ft_printf("%-4c", 0);
	printf("a: %d\n", a);
	a = printf("%-4c", 0);
	printf("a: %d\n", a);
	a = ft_printf(" %-1c %-2c %-3c ", '0', 0, '1');
	printf("a: %d\n", a);
	a = printf(" %-1c %-2c %-3c ", '0', 0, '1');
	printf("a: %d\n", a);
	a = ft_printf(" NULL %s NULL ", NULL);
	printf("a: %d\n", a);
	a = printf(" NULL %s NULL ", NULL);
	printf("a: %d\n", a);
	a = printf(" %c %c %c .\n", '0', 0, '1');
	printf("a: %d\n", a);
	a = ft_printf(" %c %c %c .\n", '0', 0, '1');
	printf("a: %d\n", a);
	ft_printf(" %p %p \n", 0, 0);
	printf(" %p %p \n", 0, 0);
	ft_printf("%c \n", '0');
	printf("%c \n", '0');
	ft_printf("%c \n", '0' - 256);
	printf("%c \n", '0' -256);
	printf("null %s \n", (char *)NULL);
	printf("##### before #####\n");
	ft_printf("null %s \n", (char *)NULL);
	printf("##### before #####\n");
	ft_printf("HELLO %s \n", "world");
	printf("HELLO %s \n", "world");
	printf("\n");
	printf("pointer %p \n", NULL);
	ft_printf("pointer %p \n", NULL);
	ft_printf("pointer %p \n", s);
	printf("pointer %p \n", s);
	printf("\n");
	ft_printf("decimal %d \n", -2147483648);
	printf("decimal %d \n", -2147483648);
	printf("\n");
	ft_printf("integer %i \n", -2147483648);
	printf("integer %i \n", -2147483648);
	printf("\n");
	ft_printf("unisgned %u \n", 42949675);
	printf("unisgned %u \n", 42949675);
	printf("\n");
	ft_printf("hex %x \n", 422);
	printf("hex %x \n", 422);
	printf("\n");
	ft_printf("HEX %X \n", 422);
	printf("HEX %X \n", 422);
	printf("\n");
	ft_putnbr_base(433, "0123456789ABCDEF");
	return (0); */
}
